### ISSUE TITLE
qt-SESAM master-branch not building on Ubuntu 15.10

### ISSUE THREAD

**Issue by dpalic** [ola-ct/Qt-SESAM#105]
Dear SESAM team,

I like the idea the project provides to the community. Therefore I tried to compile the package on both:
Ubuntu 14.04 LTS along with Ubuntu 15.10.
Sadly the build is failing on both versions with following error:

```
In file included from mainwindow.cpp:22:0:
ui_mainwindow.h: In member function ‘void Ui_MainWindow::retranslateUi(QMainWindow*)’:
ui_mainwindow.h:848:29: error: ‘class QPlainTextEdit’ has no member named ‘setPlaceholderText’
         notesPlainTextEdit->setPlaceholderText(QApplication::translate("MainWindow", "may be empty", 0));
                             ^
make[1]: *** [mainwindow.o] Error 1
make[1]: Leaving directory `/opt/Qt-SESAM/Qt-SESAM'
make: *** [sub-Qt-SESAM-make_first-ordered] Error 2
```

15.10 has the qt5.4 version, so it is not clear why this is failing?
http://packages.ubuntu.com/search?keywords=qt&searchon=names&suite=wily&section=all

Can someone help out of the dark?

**Comment by 607011** [comment]
What is the terminal command `qtdiag` telling about the currently active Qt version?

**Comment by 607011** [comment]
Tested it again a couple of minutes ago: Qt-SESAM perfectly builds on Xubuntu 15.04 with Qt 5.4.1.

**Comment by pinae** [comment]
I will make a test Build on Ubuntu 15.10 tomorrow.

**Comment by dpalic** [comment]
thank you for your very quick feedback!
Maybe some packages are missing, I followed blindly the installation. And the package make was missing in the wiki documentation. Maybe others are also missing?

**Comment by 607011** [comment]
@dpalic I'm dead sure that this is an issue of an outdated Qt version. Please check with `qtdiag` that you're using Qt 5.4 or later.

**Comment by pinae** [comment]
I built the current version (a54a0d2..9cd9a05) without problems.

@dpalic Something has to be different on your Ubuntu compared to mine. Any idea what that might be?

**Comment by 607011** [comment]
Thx, @pinae Which Linux distro? Which Qt version? Which compiler?

**Comment by pinae** [comment]
Ubuntu 15.10, Qt 5.4.2, gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010

**Comment by 607011** [comment]
:+1: @pinae thx

**Comment by 607011** [comment]
@dpalic RSVP ;-)

**Comment by dpalic** [comment]
Hello together,
thank you for the great support.
I have upgraded the machine to 16.04 (dev) now it was building.
But I had a issue on the upgrade, that a package was corrupted on qt, so I assume it was a open issue from the earlier upgrade from 14.04 to 15.10. (14.04 is sadly not supported by SESAM)
Since I will not be able to reproduce it right now anymore, I think the issue should be closed.

**Comment by 607011** [comment]
Thanks for the update, @dpalic.

Closing …
